apiVersion: apps/v1
kind: Deployment
metadata:
  name: delphi-admin-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delphi-admin-app
  template:
    metadata:
      labels:
        app: delphi-admin-app
    spec:
      imagePullSecrets:
        - name: 'turbotic-acr'
      containers:
        - name: delphi-admin-app
          image: turbotic.azurecr.io/delphi-admin-app:Houston-v2.5.0.63-distroless
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: BUILD_NUMBER
              value: '6394'
            - name: RELEASE_NAME
              value: 'Houston-v2.5.0.63-distroless'
            - name: DELPHI_OS_BASE_URL
              value: 'https://turbotic-poc.fiserv.co.in'                                  
            - name: SERVER_DELPHI_BASEURL_HTTPS
              value: 'http://lb-delphi-app:8088'                                  
            - name: NODE_ENV
              value: 'production'
            - name: API_LOCAL_PORT
              value: '8080'
            - name: API_VHOST_DOMAIN
              value: 'admin-turbotic-poc.fiserv.co.in'
            - name: API_VHOST_PORT
              value: '443'
            - name: API_VHOST_PROTO
              value: 'https'
            - name: MONGO_DB_CONN_STRATEGY
              value: 'ENV'                   
            - name: MONGO_DB_CONN_STRING
              value: 'mongodb://192.168.1.114:27017/turbotic-admin-terms'
            - name: IS_CHARGEBEE_DISABLED
              value: 'false'
            - name: IS_RECAPTCHA_DISABLED
              value: 'true'

---
apiVersion: v1
kind: Service
metadata:
  name: lb-delphi-admin-app
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: turbotic-delphi-admin
spec:
  selector:
    app: delphi-admin-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8080              

